### ISSUE TITLE
2.x Documentation Frequently mentions SimpleCmsBundle classes

### ISSUE THREAD

**Issue by shkkmo** [symfony-cmf/core-bundle#231]
The 2.x version of the documentation uses SimpleCmsBundle classes in almost all of it's examples, e,g:
http://symfony.com/doc/master/cmf/quick_tour/the_big_picture.html#adding-a-new-page
http://symfony.com/doc/master/cmf/quick_tour/the_model.html#creating-a-page-with-code
http://symfony.com/doc/master/cmf/quick_tour/the_router.html#loading-routes-from-the-phpcr-tree
http://symfony.com/doc/master/cmf/book/installation.html#acmemainbundle-and-simplecmsbundle
http://symfony.com/doc/master/cmf/book/installation.html#adding-new-pages
http://symfony.com/doc/master/cmf/book/simplecms.html

However, SimpleCmsBundle does not support SymfonyCMF v2. This doesn't make any sense. I see that SimpleCmsBundle is also marked and being unmaintained. However, you should either update SimpleCmsBundle enough to support SymfonyCMF v2 or update the v2 documentation to not reference SimpleCmsBundle.

**Comment by dbu** [comment]
thank your for reporting this. we are still in the process of finalizing version 2. but those usages where not on our radar. i created the following issues in the documentation repository:

https://github.com/symfony-cmf/symfony-cmf-docs/issues/827
https://github.com/symfony-cmf/symfony-cmf-docs/issues/827

i will close the issue here as we track documentation issues in the documentation repository.
